-- Find total customers number by countries
SELECT 
	country,
	COUNT(customer_id) AS Total_Customers
FROM gold.dim_customers
GROUP BY country
ORDER BY 2 DESC;

-- Find Total customers by Gender
SELECT 
	gender,
	COUNT(customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY 2 DESC;

-- Find the Total Product by category
SELECT 
	category,
	COUNT(product_key) AS Total_products
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC;

-- what is the average cost in every category
SELECT 
	category,
	AVG(product_cost)
FROM gold.dim_products
GROUP BY category
ORDER BY 2 DESC;

-- What is the Average total revenue generated for each category
SELECT
    category,
    AVG(CAST(price AS BIGINT) * sales_amount - product_cost) AS revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
    ON s.product_key = p.product_key
GROUP BY category
ORDER BY 2 DESC;

---- What is the total revenue generated for each category
SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
	ON f.product_key=p.product_key
GROUP BY p.category
ORDER BY 2 DESC;

-- What is the total revenue generated by each customer
SELECT
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON f.customer_key=c.customer_key
GROUP BY c.customer_id,c.first_name,c.last_name
ORDER BY 4 DESC;

-- What is the distribution of sold items across counttries
SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
	ON f.customer_key=c.customer_key
GROUP BY c.country
ORDER BY 2 DESC;
